services:
  front-api:
    container_name: front-api
    restart: on-failure
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development  
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    networks:
      - calculus-network    