name: Deploy App in Azure

# Dispara o workflow para push e pull request na branch 'dev'
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name:  Run script on Azure VM
        uses: cross-the-world/ssh-pipeline@master
        env:
          WELCOME: "ssh pipeline"
        with:
          host: ${{ secrets.IP_VM_AZURE_DEV }}
          user: ${{ secrets.USER_VM_AZURE_DEV }}
          pass: ${{ secrets.USER_VM_AZURE_DEV }}
          port: 22
          connect_timeout: 10s
          script: |
            cd /home/Calculus-admin1/app 
            sudo su
            ./run_npm_tmux.sh
